package ec.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2015-01-20T08:14:16.272-05:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebServiceClient(name = "FinancialService", 
                  wsdlLocation = "http://localhost:8080/proxy_rest/FinancialService?wsdl",
                  targetNamespace = "urn:ec.com.softwareevolutivo:client.financial.proxy:1.0") 
public class FinancialService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:ec.com.softwareevolutivo:client.financial.proxy:1.0", "FinancialService");
    public final static QName FinancialServicePort = new QName("urn:ec.com.softwareevolutivo:client.financial.proxy:1.0", "FinancialServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/proxy_rest/FinancialService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FinancialService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/proxy_rest/FinancialService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FinancialService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FinancialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinancialService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinancialService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FinancialService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FinancialServicePortType
     */
    @WebEndpoint(name = "FinancialServicePort")
    public FinancialServicePortType getFinancialServicePort() {
        return super.getPort(FinancialServicePort, FinancialServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialServicePortType
     */
    @WebEndpoint(name = "FinancialServicePort")
    public FinancialServicePortType getFinancialServicePort(WebServiceFeature... features) {
        return super.getPort(FinancialServicePort, FinancialServicePortType.class, features);
    }

}
